### PR TITLE
Add linting script to CI that checks for zod:lint

### LINKED ISSUE #106: Add linting script to CI that checks for basic design rules (snake case rules)
- camel case in zod objects is not allowed
- enums inside zod objects should be lower snake_case

This can be created as a simple script

Must run on CI

/bounty $5

### PR DESCRIPTION
**Pull request by Anshgrover23**
Fixes #106 
/claim #106 

### Description:
-  provide exact line/column numbers for errors
- which devin-ai is unable to do that.

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
Looks ok but dont change the existing spec (itll break a ton of stuff) just add ignore lines

**Comment by Anshgrover23** [comment]
@seveibar done.

**Review by seveibar — APPROVED** [review]
nice

**Comment by seveibar** [comment]
@Anshgrover23 you should break this up into multiple files e.g. `scripts/zod-lint/run.ts`, `scripts/zod-lint/snake-case-rule.ts`, `scripts/zod-lint/no-camel-case-rule.ts` so that we can easily add more without creating a giant file

but nice work

**Pull request merged**
